/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC)
#   if (__SUNPRO_CC <= 0x560)
#     define SWIGTEMPLATEDISAMBIGUATOR template
#   else
#     define SWIGTEMPLATEDISAMBIGUATOR 
#   endif
# else
#   define SWIGTEMPLATEDISAMBIGUATOR 
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTELC__)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" } };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


/* Includes the header in the wrapper code */
#include "../../engine/kowalski.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_kowalski_KowalskiJNI_KWL_1NO_1ERROR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  kwlError result;
  
  (void)jenv;
  (void)jcls;
  result = (kwlError)KWL_NO_ERROR;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_kowalski_KowalskiJNI_KWL_1INVALID_1HANDLE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(int)KWL_INVALID_HANDLE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_kowalski_KowalskiJNI_kwlEventGetHandle(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jint jresult = 0 ;
  char *arg1 = (char *) (char *)0 ;
  kwlEventHandle result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (kwlEventHandle)kwlEventGetHandle((char const *)arg1);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_kowalski_KowalskiJNI_kwlEventDefinitionGetHandle(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jint jresult = 0 ;
  char *arg1 = (char *) (char *)0 ;
  kwlEventDefinitionHandle result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (kwlEventDefinitionHandle)kwlEventDefinitionGetHandle((char const *)arg1);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_kowalski_KowalskiJNI_kwlEventCreateWithFile(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2) {
  jint jresult = 0 ;
  char *arg1 = (char *) (char *)0 ;
  kwlEventType arg2 ;
  kwlEventHandle result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (kwlEventType)jarg2; 
  result = (kwlEventHandle)kwlEventCreateWithFile((char const *)arg1,arg2);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_kowalski_KowalskiJNI_kwlEventCreateWithBuffer(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3, jint jarg4) {
  jint jresult = 0 ;
  short *arg1 = (short *) 0 ;
  int arg2 ;
  int arg3 ;
  kwlEventType arg4 ;
  kwlEventHandle result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(short **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (kwlEventType)jarg4; 
  result = (kwlEventHandle)kwlEventCreateWithBuffer(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlEventRelease(JNIEnv *jenv, jclass jcls, jint jarg1) {
  kwlEventHandle arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlEventHandle)jarg1; 
  kwlEventRelease(arg1);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlEventSetPitch(JNIEnv *jenv, jclass jcls, jint jarg1, jfloat jarg2) {
  kwlEventHandle arg1 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlEventHandle)jarg1; 
  arg2 = (float)jarg2; 
  kwlEventSetPitch(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlEventSetGain(JNIEnv *jenv, jclass jcls, jint jarg1, jfloat jarg2) {
  kwlEventHandle arg1 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlEventHandle)jarg1; 
  arg2 = (float)jarg2; 
  kwlEventSetGain(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlEventSetLinearGain(JNIEnv *jenv, jclass jcls, jint jarg1, jfloat jarg2) {
  kwlEventHandle arg1 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlEventHandle)jarg1; 
  arg2 = (float)jarg2; 
  kwlEventSetLinearGain(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlEventSetPosition(JNIEnv *jenv, jclass jcls, jint jarg1, jfloat jarg2, jfloat jarg3, jfloat jarg4) {
  kwlEventHandle arg1 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlEventHandle)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  kwlEventSetPosition(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlEventSetVelocity(JNIEnv *jenv, jclass jcls, jint jarg1, jfloat jarg2, jfloat jarg3, jfloat jarg4) {
  kwlEventHandle arg1 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlEventHandle)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  kwlEventSetVelocity(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlEventSetOrientation(JNIEnv *jenv, jclass jcls, jint jarg1, jfloat jarg2, jfloat jarg3, jfloat jarg4) {
  kwlEventHandle arg1 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlEventHandle)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  kwlEventSetOrientation(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlEventSetBalance(JNIEnv *jenv, jclass jcls, jint jarg1, jfloat jarg2) {
  kwlEventHandle arg1 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlEventHandle)jarg1; 
  arg2 = (float)jarg2; 
  kwlEventSetBalance(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlEventStart(JNIEnv *jenv, jclass jcls, jint jarg1) {
  kwlEventHandle arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlEventHandle)jarg1; 
  kwlEventStart(arg1);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlEventStartOneShot(JNIEnv *jenv, jclass jcls, jint jarg1) {
  kwlEventDefinitionHandle arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlEventDefinitionHandle)jarg1; 
  kwlEventStartOneShot(arg1);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlEventStartOneShotAt(JNIEnv *jenv, jclass jcls, jint jarg1, jfloat jarg2, jfloat jarg3, jfloat jarg4) {
  kwlEventDefinitionHandle arg1 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlEventDefinitionHandle)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  kwlEventStartOneShotAt(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlEventStartFade(JNIEnv *jenv, jclass jcls, jint jarg1, jfloat jarg2) {
  kwlEventHandle arg1 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlEventHandle)jarg1; 
  arg2 = (float)jarg2; 
  kwlEventStartFade(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlEventStop(JNIEnv *jenv, jclass jcls, jint jarg1) {
  kwlEventHandle arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlEventHandle)jarg1; 
  kwlEventStop(arg1);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlEventStopFade(JNIEnv *jenv, jclass jcls, jint jarg1, jfloat jarg2) {
  kwlEventHandle arg1 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlEventHandle)jarg1; 
  arg2 = (float)jarg2; 
  kwlEventStopFade(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlEventPause(JNIEnv *jenv, jclass jcls, jint jarg1) {
  kwlEventHandle arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlEventHandle)jarg1; 
  kwlEventPause(arg1);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlEventResume(JNIEnv *jenv, jclass jcls, jint jarg1) {
  kwlEventHandle arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlEventHandle)jarg1; 
  kwlEventResume(arg1);
}


SWIGEXPORT jint JNICALL Java_kowalski_KowalskiJNI_kwlEventIsPlaying(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  kwlEventHandle arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlEventHandle)jarg1; 
  result = (int)kwlEventIsPlaying(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_kowalski_KowalskiJNI_kwlMixBusGetHandle(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jint jresult = 0 ;
  char *arg1 = (char *) (char *)0 ;
  kwlMixBusHandle result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (kwlMixBusHandle)kwlMixBusGetHandle((char const *)arg1);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlMixBusSetPitch(JNIEnv *jenv, jclass jcls, jint jarg1, jfloat jarg2) {
  kwlMixBusHandle arg1 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlMixBusHandle)jarg1; 
  arg2 = (float)jarg2; 
  kwlMixBusSetPitch(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlMixBusSetGain(JNIEnv *jenv, jclass jcls, jint jarg1, jfloat jarg2) {
  kwlMixBusHandle arg1 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlMixBusHandle)jarg1; 
  arg2 = (float)jarg2; 
  kwlMixBusSetGain(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlMixBusSetLinearGain(JNIEnv *jenv, jclass jcls, jint jarg1, jfloat jarg2) {
  kwlMixBusHandle arg1 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlMixBusHandle)jarg1; 
  arg2 = (float)jarg2; 
  kwlMixBusSetLinearGain(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_kowalski_KowalskiJNI_kwlMixPresetGetHandle(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jint jresult = 0 ;
  char *arg1 = (char *) (char *)0 ;
  kwlMixPresetHandle result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (kwlMixPresetHandle)kwlMixPresetGetHandle((char const *)arg1);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlMixPresetFadeTo(JNIEnv *jenv, jclass jcls, jint jarg1) {
  kwlMixPresetHandle arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlMixPresetHandle)jarg1; 
  kwlMixPresetFadeTo(arg1);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlMixPresetSet(JNIEnv *jenv, jclass jcls, jint jarg1) {
  kwlMixPresetHandle arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlMixPresetHandle)jarg1; 
  kwlMixPresetSet(arg1);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlListenerSetPosition(JNIEnv *jenv, jclass jcls, jfloat jarg1, jfloat jarg2, jfloat jarg3) {
  float arg1 ;
  float arg2 ;
  float arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (float)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  kwlListenerSetPosition(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlListenerSetVelocity(JNIEnv *jenv, jclass jcls, jfloat jarg1, jfloat jarg2, jfloat jarg3) {
  float arg1 ;
  float arg2 ;
  float arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (float)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  kwlListenerSetVelocity(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlListenerSetOrientation(JNIEnv *jenv, jclass jcls, jfloat jarg1, jfloat jarg2, jfloat jarg3, jfloat jarg4, jfloat jarg5, jfloat jarg6) {
  float arg1 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  float arg5 ;
  float arg6 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (float)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  arg5 = (float)jarg5; 
  arg6 = (float)jarg6; 
  kwlListenerSetOrientation(arg1,arg2,arg3,arg4,arg5,arg6);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlSetDistanceAttenuationModel(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jfloat jarg3, jfloat jarg4, jfloat jarg5) {
  kwlDistanceAttenuationModel arg1 ;
  int arg2 ;
  float arg3 ;
  float arg4 ;
  float arg5 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlDistanceAttenuationModel)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  arg5 = (float)jarg5; 
  kwlSetDistanceAttenuationModel(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlSetDopplerShiftParameters(JNIEnv *jenv, jclass jcls, jfloat jarg1, jfloat jarg2) {
  float arg1 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (float)jarg1; 
  arg2 = (float)jarg2; 
  kwlSetDopplerShiftParameters(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlSetConeAttenuationEnabled(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  int arg1 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  kwlSetConeAttenuationEnabled(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlSetListenerConeParameters(JNIEnv *jenv, jclass jcls, jfloat jarg1, jfloat jarg2, jfloat jarg3) {
  float arg1 ;
  float arg2 ;
  float arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (float)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  kwlSetListenerConeParameters(arg1,arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_kowalski_KowalskiJNI_kwlGetNumFramesMixed(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  result = (unsigned int)kwlGetNumFramesMixed();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_kowalski_KowalskiJNI_kwlWaveBankLoad(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jint jresult = 0 ;
  char *arg1 = (char *) (char *)0 ;
  kwlWaveBankHandle result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (kwlWaveBankHandle)kwlWaveBankLoad((char const *)arg1);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlWaveBankUnload(JNIEnv *jenv, jclass jcls, jint jarg1) {
  kwlWaveBankHandle arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlWaveBankHandle)jarg1; 
  kwlWaveBankUnload(arg1);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlWaveBankUnloadBlocking(JNIEnv *jenv, jclass jcls, jint jarg1) {
  kwlWaveBankHandle arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlWaveBankHandle)jarg1; 
  kwlWaveBankUnloadBlocking(arg1);
}


SWIGEXPORT jint JNICALL Java_kowalski_KowalskiJNI_kwlWaveBankIsLoaded(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  kwlWaveBankHandle arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (kwlWaveBankHandle)jarg1; 
  result = (int)kwlWaveBankIsLoaded(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_kowalski_KowalskiJNI_kwlIsEngineInitialized(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)kwlIsEngineInitialized();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlDeinitialize(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  kwlDeinitialize();
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlInitialize(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jint jarg3, jint jarg4) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  kwlInitialize(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlEngineDataLoad(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) (char *)0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  kwlEngineDataLoad((char const *)arg1);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlEngineDataUnload(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  kwlEngineDataUnload();
}


SWIGEXPORT jint JNICALL Java_kowalski_KowalskiJNI_kwlEngineDataIsLoaded(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)kwlEngineDataIsLoaded();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlMixerResume(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  kwlMixerResume();
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlMixerPause(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  kwlMixerPause();
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlEnableLevelMetering(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  kwlEnableLevelMetering();
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlDisableLevelMetering(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  kwlDisableLevelMetering();
}


SWIGEXPORT jfloat JNICALL Java_kowalski_KowalskiJNI_kwlGetLevelLeft(JNIEnv *jenv, jclass jcls) {
  jfloat jresult = 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  result = (float)kwlGetLevelLeft();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_kowalski_KowalskiJNI_kwlGetLevelRight(JNIEnv *jenv, jclass jcls) {
  jfloat jresult = 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  result = (float)kwlGetLevelRight();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_kowalski_KowalskiJNI_kwlHasClipped(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)kwlHasClipped();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_kowalski_KowalskiJNI_kwlUpdate(JNIEnv *jenv, jclass jcls, jfloat jarg1) {
  float arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (float)jarg1; 
  kwlUpdate(arg1);
}


SWIGEXPORT jint JNICALL Java_kowalski_KowalskiJNI_kwlGetError(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  kwlError result;
  
  (void)jenv;
  (void)jcls;
  result = (kwlError)kwlGetError();
  jresult = (jint)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

