/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kowalski;

public final class kwlError {
  public final static kwlError KWL_NO_ERROR = new kwlError("KWL_NO_ERROR", KowalskiJNI.KWL_NO_ERROR_get());
  public final static kwlError KWL_INVALID_MIX_BUS_HANDLE = new kwlError("KWL_INVALID_MIX_BUS_HANDLE");
  public final static kwlError KWL_INVALID_EVENT_INSTANCE_HANDLE = new kwlError("KWL_INVALID_EVENT_INSTANCE_HANDLE");
  public final static kwlError KWL_INVALID_EVENT_DEFINITION_HANDLE = new kwlError("KWL_INVALID_EVENT_DEFINITION_HANDLE");
  public final static kwlError KWL_INVALID_MIX_PRESET_HANDLE = new kwlError("KWL_INVALID_MIX_PRESET_HANDLE");
  public final static kwlError KWL_NO_FREE_EVENT_INSTANCES = new kwlError("KWL_NO_FREE_EVENT_INSTANCES");
  public final static kwlError KWL_INVALID_WAVE_BANK_HANDLE = new kwlError("KWL_INVALID_WAVE_BANK_HANDLE");
  public final static kwlError KWL_UNKNOWN_MIX_PRESET_ID = new kwlError("KWL_UNKNOWN_MIX_PRESET_ID");
  public final static kwlError KWL_UNKNOWN_EVENT_DEFINITION_ID = new kwlError("KWL_UNKNOWN_EVENT_DEFINITION_ID");
  public final static kwlError KWL_UNKNOWN_MIX_BUS_ID = new kwlError("KWL_UNKNOWN_MIX_BUS_ID");
  public final static kwlError KWL_ENGINE_IS_NOT_INITIALIZED = new kwlError("KWL_ENGINE_IS_NOT_INITIALIZED");
  public final static kwlError KWL_ENGINE_ALREADY_INITIALIZED = new kwlError("KWL_ENGINE_ALREADY_INITIALIZED");
  public final static kwlError KWL_INVALID_PARAMETER_VALUE = new kwlError("KWL_INVALID_PARAMETER_VALUE");
  public final static kwlError KWL_FILE_NOT_FOUND = new kwlError("KWL_FILE_NOT_FOUND");
  public final static kwlError KWL_UNKNOWN_FILE_FORMAT = new kwlError("KWL_UNKNOWN_FILE_FORMAT");
  public final static kwlError KWL_UNSUPPORTED_SAMPLE_RATE = new kwlError("KWL_UNSUPPORTED_SAMPLE_RATE");
  public final static kwlError KWL_UNSUPPORTED_NUM_OUTPUT_CHANNELS = new kwlError("KWL_UNSUPPORTED_NUM_OUTPUT_CHANNELS");
  public final static kwlError KWL_UNSUPPORTED_NUM_INPUT_CHANNELS = new kwlError("KWL_UNSUPPORTED_NUM_INPUT_CHANNELS");
  public final static kwlError KWL_ENGINE_DATA_NOT_LOADED = new kwlError("KWL_ENGINE_DATA_NOT_LOADED");
  public final static kwlError KWL_ENGINE_ALREADY_LOADED = new kwlError("KWL_ENGINE_ALREADY_LOADED");
  public final static kwlError KWL_MESSAGE_QUEUE_FULL = new kwlError("KWL_MESSAGE_QUEUE_FULL");
  public final static kwlError KWL_NO_MATCHING_WAVE_BANK = new kwlError("KWL_NO_MATCHING_WAVE_BANK");
  public final static kwlError KWL_WAVE_BANK_ENTRY_MISMATCH = new kwlError("KWL_WAVE_BANK_ENTRY_MISMATCH");
  public final static kwlError KWL_UNSUPPORTED_ENCODING = new kwlError("KWL_UNSUPPORTED_ENCODING");
  public final static kwlError KWL_NO_FREE_DECODERS = new kwlError("KWL_NO_FREE_DECODERS");
  public final static kwlError KWL_LEVEL_METERING_DISABLED = new kwlError("KWL_LEVEL_METERING_DISABLED");
  public final static kwlError KWL_EVENT_IS_NOT_POSITIONAL = new kwlError("KWL_EVENT_IS_NOT_POSITIONAL");
  public final static kwlError KWL_EVENT_IS_NOT_NONPOSITIONAL = new kwlError("KWL_EVENT_IS_NOT_NONPOSITIONAL");
  public final static kwlError KWL_POSITIONAL_EVENT_MUST_BE_MONO = new kwlError("KWL_POSITIONAL_EVENT_MUST_BE_MONO");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static kwlError swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + kwlError.class + " with value " + swigValue);
  }

  private kwlError(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private kwlError(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private kwlError(String swigName, kwlError swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static kwlError[] swigValues = { KWL_NO_ERROR, KWL_INVALID_MIX_BUS_HANDLE, KWL_INVALID_EVENT_INSTANCE_HANDLE, KWL_INVALID_EVENT_DEFINITION_HANDLE, KWL_INVALID_MIX_PRESET_HANDLE, KWL_NO_FREE_EVENT_INSTANCES, KWL_INVALID_WAVE_BANK_HANDLE, KWL_UNKNOWN_MIX_PRESET_ID, KWL_UNKNOWN_EVENT_DEFINITION_ID, KWL_UNKNOWN_MIX_BUS_ID, KWL_ENGINE_IS_NOT_INITIALIZED, KWL_ENGINE_ALREADY_INITIALIZED, KWL_INVALID_PARAMETER_VALUE, KWL_FILE_NOT_FOUND, KWL_UNKNOWN_FILE_FORMAT, KWL_UNSUPPORTED_SAMPLE_RATE, KWL_UNSUPPORTED_NUM_OUTPUT_CHANNELS, KWL_UNSUPPORTED_NUM_INPUT_CHANNELS, KWL_ENGINE_DATA_NOT_LOADED, KWL_ENGINE_ALREADY_LOADED, KWL_MESSAGE_QUEUE_FULL, KWL_NO_MATCHING_WAVE_BANK, KWL_WAVE_BANK_ENTRY_MISMATCH, KWL_UNSUPPORTED_ENCODING, KWL_NO_FREE_DECODERS, KWL_LEVEL_METERING_DISABLED, KWL_EVENT_IS_NOT_POSITIONAL, KWL_EVENT_IS_NOT_NONPOSITIONAL, KWL_POSITIONAL_EVENT_MUST_BE_MONO };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

