/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kowalski;

class KowalskiJNI {
  public final static native int KWL_NO_ERROR_get();
  public final static native int KWL_INVALID_HANDLE_get();
  public final static native int kwlEventGetHandle(String jarg1);
  public final static native int kwlEventDefinitionGetHandle(String jarg1);
  public final static native int kwlEventCreateWithFile(String jarg1, int jarg2);
  public final static native int kwlEventCreateWithBuffer(long jarg1, int jarg2, int jarg3, int jarg4);
  public final static native void kwlEventRelease(int jarg1);
  public final static native void kwlEventSetPitch(int jarg1, float jarg2);
  public final static native void kwlEventSetGain(int jarg1, float jarg2);
  public final static native void kwlEventSetLinearGain(int jarg1, float jarg2);
  public final static native void kwlEventSetPosition(int jarg1, float jarg2, float jarg3, float jarg4);
  public final static native void kwlEventSetVelocity(int jarg1, float jarg2, float jarg3, float jarg4);
  public final static native void kwlEventSetOrientation(int jarg1, float jarg2, float jarg3, float jarg4);
  public final static native void kwlEventSetBalance(int jarg1, float jarg2);
  public final static native void kwlEventStart(int jarg1);
  public final static native void kwlEventStartOneShot(int jarg1);
  public final static native void kwlEventStartOneShotAt(int jarg1, float jarg2, float jarg3, float jarg4);
  public final static native void kwlEventStartFade(int jarg1, float jarg2);
  public final static native void kwlEventStop(int jarg1);
  public final static native void kwlEventStopFade(int jarg1, float jarg2);
  public final static native void kwlEventPause(int jarg1);
  public final static native void kwlEventResume(int jarg1);
  public final static native int kwlEventIsPlaying(int jarg1);
  public final static native int kwlMixBusGetHandle(String jarg1);
  public final static native void kwlMixBusSetPitch(int jarg1, float jarg2);
  public final static native void kwlMixBusSetGain(int jarg1, float jarg2);
  public final static native void kwlMixBusSetLinearGain(int jarg1, float jarg2);
  public final static native int kwlMixPresetGetHandle(String jarg1);
  public final static native void kwlMixPresetFadeTo(int jarg1);
  public final static native void kwlMixPresetSet(int jarg1);
  public final static native void kwlListenerSetPosition(float jarg1, float jarg2, float jarg3);
  public final static native void kwlListenerSetVelocity(float jarg1, float jarg2, float jarg3);
  public final static native void kwlListenerSetOrientation(float jarg1, float jarg2, float jarg3, float jarg4, float jarg5, float jarg6);
  public final static native void kwlSetDistanceAttenuationModel(int jarg1, int jarg2, float jarg3, float jarg4, float jarg5);
  public final static native void kwlSetDopplerShiftParameters(float jarg1, float jarg2);
  public final static native void kwlSetConeAttenuationEnabled(int jarg1, int jarg2);
  public final static native void kwlSetListenerConeParameters(float jarg1, float jarg2, float jarg3);
  public final static native long kwlGetNumFramesMixed();
  public final static native int kwlWaveBankLoad(String jarg1);
  public final static native void kwlWaveBankUnload(int jarg1);
  public final static native void kwlWaveBankUnloadBlocking(int jarg1);
  public final static native int kwlWaveBankIsLoaded(int jarg1);
  public final static native int kwlIsEngineInitialized();
  public final static native void kwlDeinitialize();
  public final static native void kwlInitialize(int jarg1, int jarg2, int jarg3, int jarg4);
  public final static native void kwlEngineDataLoad(String jarg1);
  public final static native void kwlEngineDataUnload();
  public final static native int kwlEngineDataIsLoaded();
  public final static native void kwlMixerResume();
  public final static native void kwlMixerPause();
  public final static native void kwlEnableLevelMetering();
  public final static native void kwlDisableLevelMetering();
  public final static native float kwlGetLevelLeft();
  public final static native float kwlGetLevelRight();
  public final static native int kwlHasClipped();
  public final static native void kwlUpdate(float jarg1);
  public final static native int kwlGetError();
}
