/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kowalski;

public final class kwlDistanceAttenuationModel {
  public final static kwlDistanceAttenuationModel KWL_INV_DISTANCE = new kwlDistanceAttenuationModel("KWL_INV_DISTANCE");
  public final static kwlDistanceAttenuationModel KWL_LINEAR = new kwlDistanceAttenuationModel("KWL_LINEAR");
  public final static kwlDistanceAttenuationModel KWL_CONSTANT = new kwlDistanceAttenuationModel("KWL_CONSTANT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static kwlDistanceAttenuationModel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + kwlDistanceAttenuationModel.class + " with value " + swigValue);
  }

  private kwlDistanceAttenuationModel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private kwlDistanceAttenuationModel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private kwlDistanceAttenuationModel(String swigName, kwlDistanceAttenuationModel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static kwlDistanceAttenuationModel[] swigValues = { KWL_INV_DISTANCE, KWL_LINEAR, KWL_CONSTANT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

