//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-03/31/2009 04:14 PM(snajper)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.14 at 06:13:26 PM CEST 
//


package kowalski.tools.data.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A set of mix bus parameters, one per mix bus in the project.
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="mixBus" use="required" type="{}identifierString" />
 *       &lt;attribute name="leftGain" use="required" type="{}gainFloat" />
 *       &lt;attribute name="rightGain" use="required" type="{}gainFloat" />
 *       &lt;attribute name="pitch" use="required" type="{}pitchFloat" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "MixBusParameters")
public class MixBusParameters {

    @XmlAttribute(required = true)
    protected String mixBus;
    @XmlAttribute(required = true)
    protected float leftGain;
    @XmlAttribute(required = true)
    protected float rightGain;
    @XmlAttribute(required = true)
    protected float pitch;

    /**
     * Gets the value of the mixBus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMixBus() {
        return mixBus;
    }

    /**
     * Sets the value of the mixBus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMixBus(String value) {
        this.mixBus = value;
    }

    /**
     * Gets the value of the leftGain property.
     * 
     */
    public float getLeftGain() {
        return leftGain;
    }

    /**
     * Sets the value of the leftGain property.
     * 
     */
    public void setLeftGain(float value) {
        this.leftGain = value;
    }

    /**
     * Gets the value of the rightGain property.
     * 
     */
    public float getRightGain() {
        return rightGain;
    }

    /**
     * Sets the value of the rightGain property.
     * 
     */
    public void setRightGain(float value) {
        this.rightGain = value;
    }

    /**
     * Gets the value of the pitch property.
     * 
     */
    public float getPitch() {
        return pitch;
    }

    /**
     * Sets the value of the pitch property.
     * 
     */
    public void setPitch(float value) {
        this.pitch = value;
    }

}
