//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-03/31/2009 04:14 PM(snajper)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.14 at 06:13:26 PM CEST 
//


package kowalski.tools.data.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A group of mix presets, ie a branch node in a sound group hierarchy.
 * 
 * <p>Java class for MixPresetGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MixPresetGroup">
 *   &lt;complexContent>
 *     &lt;extension base="{}NodeWithIDAndComments">
 *       &lt;sequence>
 *         &lt;element name="MixPresetGroup" type="{}MixPresetGroup" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MixPreset" type="{}MixPreset" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MixPresetGroup", propOrder = {
    "subGroups",
    "mixPresets"
})
public class MixPresetGroup
    extends NodeWithIDAndComments
{

    @XmlElement(name = "MixPresetGroup")
    protected List<MixPresetGroup> subGroups;
    @XmlElement(name = "MixPreset")
    protected List<MixPreset> mixPresets;

    /**
     * Gets the value of the subGroups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subGroups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MixPresetGroup }
     * 
     * 
     */
    public List<MixPresetGroup> getSubGroups() {
        if (subGroups == null) {
            subGroups = new ArrayList<MixPresetGroup>();
        }
        return this.subGroups;
    }

    /**
     * Gets the value of the mixPresets property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mixPresets property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMixPresets().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MixPreset }
     * 
     * 
     */
    public List<MixPreset> getMixPresets() {
        if (mixPresets == null) {
            mixPresets = new ArrayList<MixPreset>();
        }
        return this.mixPresets;
    }

}
