//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-03/31/2009 04:14 PM(snajper)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.14 at 06:13:26 PM CEST 
//


package kowalski.tools.data.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventInstanceStealingMode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EventInstanceStealingMode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="STEAL_QUIETEST"/>
 *     &lt;enumeration value="STEAL_RANDOM"/>
 *     &lt;enumeration value="DONT_STEAL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EventInstanceStealingMode")
@XmlEnum
public enum EventInstanceStealingMode {

    STEAL_QUIETEST,
    STEAL_RANDOM,
    DONT_STEAL;

    public String value() {
        return name();
    }

    public static EventInstanceStealingMode fromValue(String v) {
        return valueOf(v);
    }

}
