//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-03/31/2009 04:14 PM(snajper)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.14 at 06:13:26 PM CEST 
//


package kowalski.tools.data.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * The root node of a Kowalski XML data document. 
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="WaveBankGroup" type="{}WaveBankGroup"/>
 *         &lt;element name="SoundGroup" type="{}SoundGroup"/>
 *         &lt;element name="EventGroup" type="{}EventGroup"/>
 *         &lt;element name="MixBus" type="{}MixBus"/>
 *         &lt;element name="MixPresetGroup" type="{}MixPresetGroup"/>
 *       &lt;/all>
 *       &lt;attribute name="audioFileRootDirectory" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="" />
 *       &lt;attribute name="audioFileRootDirectoryRelative" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="latestWaveBankDataBuildDirectory" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="latestEngineDataBuildDirectory" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="speedOfSound" type="{http://www.w3.org/2001/XMLSchema}float" default="340" />
 *       &lt;attribute name="distanceAttenuationModel" type="{}DistanceAttenuationModel" default="INVERSE_DISTANCE_CLAMPED" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "KowalskiProject")
public class KowalskiProject {

    @XmlElement(name = "WaveBankGroup", required = true)
    protected WaveBankGroup waveBankRootGroup;
    @XmlElement(name = "SoundGroup", required = true)
    protected SoundGroup soundRootGroup;
    @XmlElement(name = "EventGroup", required = true)
    protected EventGroup eventRootGroup;
    @XmlElement(name = "MixBus", required = true)
    protected MixBus masterMixBus;
    @XmlElement(name = "MixPresetGroup", required = true)
    protected MixPresetGroup mixPresetRootGroup;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String audioFileRootDirectory;
    @XmlAttribute
    protected Boolean audioFileRootDirectoryRelative;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String latestWaveBankDataBuildDirectory;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String latestEngineDataBuildDirectory;
    @XmlAttribute
    protected Float speedOfSound;
    @XmlAttribute
    protected DistanceAttenuationModel distanceAttenuationModel;
    @XmlAttribute(required = true)
    protected String version;

    /**
     * Gets the value of the waveBankRootGroup property.
     * 
     * @return
     *     possible object is
     *     {@link WaveBankGroup }
     *     
     */
    public WaveBankGroup getWaveBankRootGroup() {
        return waveBankRootGroup;
    }

    /**
     * Sets the value of the waveBankRootGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link WaveBankGroup }
     *     
     */
    public void setWaveBankRootGroup(WaveBankGroup value) {
        this.waveBankRootGroup = value;
    }

    /**
     * Gets the value of the soundRootGroup property.
     * 
     * @return
     *     possible object is
     *     {@link SoundGroup }
     *     
     */
    public SoundGroup getSoundRootGroup() {
        return soundRootGroup;
    }

    /**
     * Sets the value of the soundRootGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoundGroup }
     *     
     */
    public void setSoundRootGroup(SoundGroup value) {
        this.soundRootGroup = value;
    }

    /**
     * Gets the value of the eventRootGroup property.
     * 
     * @return
     *     possible object is
     *     {@link EventGroup }
     *     
     */
    public EventGroup getEventRootGroup() {
        return eventRootGroup;
    }

    /**
     * Sets the value of the eventRootGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventGroup }
     *     
     */
    public void setEventRootGroup(EventGroup value) {
        this.eventRootGroup = value;
    }

    /**
     * Gets the value of the masterMixBus property.
     * 
     * @return
     *     possible object is
     *     {@link MixBus }
     *     
     */
    public MixBus getMasterMixBus() {
        return masterMixBus;
    }

    /**
     * Sets the value of the masterMixBus property.
     * 
     * @param value
     *     allowed object is
     *     {@link MixBus }
     *     
     */
    public void setMasterMixBus(MixBus value) {
        this.masterMixBus = value;
    }

    /**
     * Gets the value of the mixPresetRootGroup property.
     * 
     * @return
     *     possible object is
     *     {@link MixPresetGroup }
     *     
     */
    public MixPresetGroup getMixPresetRootGroup() {
        return mixPresetRootGroup;
    }

    /**
     * Sets the value of the mixPresetRootGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link MixPresetGroup }
     *     
     */
    public void setMixPresetRootGroup(MixPresetGroup value) {
        this.mixPresetRootGroup = value;
    }

    /**
     * Gets the value of the audioFileRootDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudioFileRootDirectory() {
        if (audioFileRootDirectory == null) {
            return "";
        } else {
            return audioFileRootDirectory;
        }
    }

    /**
     * Sets the value of the audioFileRootDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudioFileRootDirectory(String value) {
        this.audioFileRootDirectory = value;
    }

    /**
     * Gets the value of the audioFileRootDirectoryRelative property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAudioFileRootDirectoryRelative() {
        if (audioFileRootDirectoryRelative == null) {
            return true;
        } else {
            return audioFileRootDirectoryRelative;
        }
    }

    /**
     * Sets the value of the audioFileRootDirectoryRelative property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAudioFileRootDirectoryRelative(Boolean value) {
        this.audioFileRootDirectoryRelative = value;
    }

    /**
     * Gets the value of the latestWaveBankDataBuildDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatestWaveBankDataBuildDirectory() {
        return latestWaveBankDataBuildDirectory;
    }

    /**
     * Sets the value of the latestWaveBankDataBuildDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatestWaveBankDataBuildDirectory(String value) {
        this.latestWaveBankDataBuildDirectory = value;
    }

    /**
     * Gets the value of the latestEngineDataBuildDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatestEngineDataBuildDirectory() {
        return latestEngineDataBuildDirectory;
    }

    /**
     * Sets the value of the latestEngineDataBuildDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatestEngineDataBuildDirectory(String value) {
        this.latestEngineDataBuildDirectory = value;
    }

    /**
     * Gets the value of the speedOfSound property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getSpeedOfSound() {
        if (speedOfSound == null) {
            return  340.0F;
        } else {
            return speedOfSound;
        }
    }

    /**
     * Sets the value of the speedOfSound property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSpeedOfSound(Float value) {
        this.speedOfSound = value;
    }

    /**
     * Gets the value of the distanceAttenuationModel property.
     * 
     * @return
     *     possible object is
     *     {@link DistanceAttenuationModel }
     *     
     */
    public DistanceAttenuationModel getDistanceAttenuationModel() {
        if (distanceAttenuationModel == null) {
            return DistanceAttenuationModel.INVERSE_DISTANCE_CLAMPED;
        } else {
            return distanceAttenuationModel;
        }
    }

    /**
     * Sets the value of the distanceAttenuationModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistanceAttenuationModel }
     *     
     */
    public void setDistanceAttenuationModel(DistanceAttenuationModel value) {
        this.distanceAttenuationModel = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
