//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-03/31/2009 04:14 PM(snajper)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.14 at 06:13:26 PM CEST 
//


package kowalski.tools.data.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kowalski.tools.data.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kowalski.tools.data.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KowalskiProject }
     * 
     */
    public KowalskiProject createKowalskiProject() {
        return new KowalskiProject();
    }

    /**
     * Create an instance of {@link SoundGroup }
     * 
     */
    public SoundGroup createSoundGroup() {
        return new SoundGroup();
    }

    /**
     * Create an instance of {@link NodeWithIDAndComments }
     * 
     */
    public NodeWithIDAndComments createNodeWithIDAndComments() {
        return new NodeWithIDAndComments();
    }

    /**
     * Create an instance of {@link MixPresetGroup }
     * 
     */
    public MixPresetGroup createMixPresetGroup() {
        return new MixPresetGroup();
    }

    /**
     * Create an instance of {@link AudioData }
     * 
     */
    public AudioData createAudioData() {
        return new AudioData();
    }

    /**
     * Create an instance of {@link EventGroup }
     * 
     */
    public EventGroup createEventGroup() {
        return new EventGroup();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link MixPreset }
     * 
     */
    public MixPreset createMixPreset() {
        return new MixPreset();
    }

    /**
     * Create an instance of {@link WaveBank }
     * 
     */
    public WaveBank createWaveBank() {
        return new WaveBank();
    }

    /**
     * Create an instance of {@link MixBus }
     * 
     */
    public MixBus createMixBus() {
        return new MixBus();
    }

    /**
     * Create an instance of {@link AudioDataReference }
     * 
     */
    public AudioDataReference createAudioDataReference() {
        return new AudioDataReference();
    }

    /**
     * Create an instance of {@link MixBusParameters }
     * 
     */
    public MixBusParameters createMixBusParameters() {
        return new MixBusParameters();
    }

    /**
     * Create an instance of {@link NodeWithExpansionState }
     * 
     */
    public NodeWithExpansionState createNodeWithExpansionState() {
        return new NodeWithExpansionState();
    }

    /**
     * Create an instance of {@link WaveBankGroup }
     * 
     */
    public WaveBankGroup createWaveBankGroup() {
        return new WaveBankGroup();
    }

    /**
     * Create an instance of {@link SoundReference }
     * 
     */
    public SoundReference createSoundReference() {
        return new SoundReference();
    }

    /**
     * Create an instance of {@link Sound }
     * 
     */
    public Sound createSound() {
        return new Sound();
    }

}
