//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-03/31/2009 04:14 PM(snajper)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.14 at 06:13:26 PM CEST 
//


package kowalski.tools.data.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A sound source defined by a set of PCM audio files along with a set of playback behavior parameters.
 * 
 * <p>Java class for Sound complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Sound">
 *   &lt;complexContent>
 *     &lt;extension base="{}NodeWithIDAndComments">
 *       &lt;sequence>
 *         &lt;element ref="{}AudioDataReference" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="playbackCount" type="{}playbackCountInt" default="1" />
 *       &lt;attribute name="deferStop" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="playbackMode" type="{}SoundPlaybackMode" default="SEQUENTIAL" />
 *       &lt;attribute name="gain" type="{}gainFloat" default="1.0" />
 *       &lt;attribute name="gainVariationPercent" type="{http://www.w3.org/2001/XMLSchema}float" default="0.0" />
 *       &lt;attribute name="pitch" type="{}pitchFloat" default="1.0" />
 *       &lt;attribute name="pitchVariationPercent" type="{http://www.w3.org/2001/XMLSchema}float" default="0.0" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Sound", propOrder = {
    "audioDataReferences"
})
public class Sound
    extends NodeWithIDAndComments
{

    @XmlElement(name = "AudioDataReference")
    protected List<AudioDataReference> audioDataReferences;
    @XmlAttribute
    protected Integer playbackCount;
    @XmlAttribute
    protected Boolean deferStop;
    @XmlAttribute
    protected SoundPlaybackMode playbackMode;
    @XmlAttribute
    protected Float gain;
    @XmlAttribute
    protected Float gainVariationPercent;
    @XmlAttribute
    protected Float pitch;
    @XmlAttribute
    protected Float pitchVariationPercent;

    /**
     * Gets the value of the audioDataReferences property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the audioDataReferences property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAudioDataReferences().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AudioDataReference }
     * 
     * 
     */
    public List<AudioDataReference> getAudioDataReferences() {
        if (audioDataReferences == null) {
            audioDataReferences = new ArrayList<AudioDataReference>();
        }
        return this.audioDataReferences;
    }

    /**
     * Gets the value of the playbackCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getPlaybackCount() {
        if (playbackCount == null) {
            return  1;
        } else {
            return playbackCount;
        }
    }

    /**
     * Sets the value of the playbackCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPlaybackCount(Integer value) {
        this.playbackCount = value;
    }

    /**
     * Gets the value of the deferStop property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDeferStop() {
        if (deferStop == null) {
            return false;
        } else {
            return deferStop;
        }
    }

    /**
     * Sets the value of the deferStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeferStop(Boolean value) {
        this.deferStop = value;
    }

    /**
     * Gets the value of the playbackMode property.
     * 
     * @return
     *     possible object is
     *     {@link SoundPlaybackMode }
     *     
     */
    public SoundPlaybackMode getPlaybackMode() {
        if (playbackMode == null) {
            return SoundPlaybackMode.SEQUENTIAL;
        } else {
            return playbackMode;
        }
    }

    /**
     * Sets the value of the playbackMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoundPlaybackMode }
     *     
     */
    public void setPlaybackMode(SoundPlaybackMode value) {
        this.playbackMode = value;
    }

    /**
     * Gets the value of the gain property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getGain() {
        if (gain == null) {
            return  1.0F;
        } else {
            return gain;
        }
    }

    /**
     * Sets the value of the gain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setGain(Float value) {
        this.gain = value;
    }

    /**
     * Gets the value of the gainVariationPercent property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getGainVariationPercent() {
        if (gainVariationPercent == null) {
            return  0.0F;
        } else {
            return gainVariationPercent;
        }
    }

    /**
     * Sets the value of the gainVariationPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setGainVariationPercent(Float value) {
        this.gainVariationPercent = value;
    }

    /**
     * Gets the value of the pitch property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getPitch() {
        if (pitch == null) {
            return  1.0F;
        } else {
            return pitch;
        }
    }

    /**
     * Sets the value of the pitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPitch(Float value) {
        this.pitch = value;
    }

    /**
     * Gets the value of the pitchVariationPercent property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getPitchVariationPercent() {
        if (pitchVariationPercent == null) {
            return  0.0F;
        } else {
            return pitchVariationPercent;
        }
    }

    /**
     * Sets the value of the pitchVariationPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPitchVariationPercent(Float value) {
        this.pitchVariationPercent = value;
    }

}
