//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-03/31/2009 04:14 PM(snajper)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.14 at 06:13:26 PM CEST 
//


package kowalski.tools.data.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A group of sound definitions, ie a branch node in a sound group hierarchy.
 * 
 * <p>Java class for SoundGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SoundGroup">
 *   &lt;complexContent>
 *     &lt;extension base="{}NodeWithIDAndComments">
 *       &lt;sequence>
 *         &lt;element name="SoundGroup" type="{}SoundGroup" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Sound" type="{}Sound" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoundGroup", propOrder = {
    "subGroups",
    "sounds"
})
public class SoundGroup
    extends NodeWithIDAndComments
{

    @XmlElement(name = "SoundGroup")
    protected List<SoundGroup> subGroups;
    @XmlElement(name = "Sound")
    protected List<Sound> sounds;

    /**
     * Gets the value of the subGroups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subGroups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SoundGroup }
     * 
     * 
     */
    public List<SoundGroup> getSubGroups() {
        if (subGroups == null) {
            subGroups = new ArrayList<SoundGroup>();
        }
        return this.subGroups;
    }

    /**
     * Gets the value of the sounds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sounds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSounds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sound }
     * 
     * 
     */
    public List<Sound> getSounds() {
        if (sounds == null) {
            sounds = new ArrayList<Sound>();
        }
        return this.sounds;
    }

}
