//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-03/31/2009 04:14 PM(snajper)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.14 at 06:13:26 PM CEST 
//


package kowalski.tools.data.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WaveBankGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WaveBankGroup">
 *   &lt;complexContent>
 *     &lt;extension base="{}NodeWithIDAndComments">
 *       &lt;sequence>
 *         &lt;element name="WaveBankGroup" type="{}WaveBankGroup" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="WaveBank" type="{}WaveBank" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WaveBankGroup", propOrder = {
    "subGroups",
    "waveBanks"
})
public class WaveBankGroup
    extends NodeWithIDAndComments
{

    @XmlElement(name = "WaveBankGroup")
    protected List<WaveBankGroup> subGroups;
    @XmlElement(name = "WaveBank")
    protected List<WaveBank> waveBanks;

    /**
     * Gets the value of the subGroups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subGroups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WaveBankGroup }
     * 
     * 
     */
    public List<WaveBankGroup> getSubGroups() {
        if (subGroups == null) {
            subGroups = new ArrayList<WaveBankGroup>();
        }
        return this.subGroups;
    }

    /**
     * Gets the value of the waveBanks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the waveBanks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWaveBanks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WaveBank }
     * 
     * 
     */
    public List<WaveBank> getWaveBanks() {
        if (waveBanks == null) {
            waveBanks = new ArrayList<WaveBank>();
        }
        return this.waveBanks;
    }

}
